steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['ci']
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'rsync', '-r', 'dist/', 'gs://$_BUCKET']
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['web', 'set', '-m', 'index.html', '-e', 'index.html', 'gs://$_BUCKET']
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'setmeta', '-h', 'Cache-Control:public,max-age=3600', 'gs://$_BUCKET/**']
timeout: '1200s'
substitutions:
  _BUCKET: "your-bucket-name"
